import Card from '@/components/Card'
import Cat from '../components/Cat';
import Head from 'next/head'


import { createContext, useEffect,useState } from 'react';
import Coura from '../components/Coura'
import TopNews from '../components/TopNews';
import BottomNews from '../components/BottomNews';






export default function Home() {
  
  return (


    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@900&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main className=''>
        <div className='mx-5' >
    <div className='mt-20'>
      <div className='flex flex-col md:flex-row    gap-2 '>
<Coura/>
<TopNews/>
      </div>
      <h1 className='loho text-xl font-extrabold mt-4 flex justify-center '>[Top News]</h1>
      <Cat/>
      <BottomNews/>
      </div>      

   

        </div>
      </main>
    </>
  )
}
